name: Publish

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - run: dotnet workload install wasm-tools
    - name: Cache Build Artifact
      uses: actions/cache@v2.1.7
      with:
        path: bin/Release/net6.0/publish
        key: bwasm-build
    - name: Build
      run: dotnet publish -c Release
    - name: Deploy
      uses: s0/git-publish-subdir-action@v2.5.0
      env:
        REPO: self
        BRANCH: public
        FOLDER: bin/Release/net6.0/publish/wwwroot
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
